project:
  execute-dir: project
  output-dir: .

format:
  html:
    html-math-method: katex
    toc: false
    embed-resources: true
  pdf:
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm
  docx:
    execute:
      echo: false
      warning: false

editor: source