default_selection <- list()
default_selection[["Suwannee River"]] = list(strata = TRUE,
                                             method = "center-line",
                                             primary = c(10), 
                                             alternate = c(5),
                                             map_lims_x = NA,
                                             map_lims_y = NA)
default_selection[["Santa Fe River"]] = list(strata = TRUE, 
                                             method = "center-line",
                                             primary = c("1" = 5,
                                                         "2" = 10,
                                                         "3" = 14,
                                                         "4" = 7), 
                                             alternate = c("1" = 2,
                                                           "2" = 3,
                                                           "3" = 3,
                                                           "4" = 3),
                                             map_lims_x = c(-82.88831, -82.52220),
                                             map_lims_y = c(29.82345, 29.95743))
default_selection[["Ocklawaha River"]] = list(strata = TRUE, 
                                              method = "grid",
                                              primary = c("1_Run" = 5,
                                                          "2_Run" = 6,
                                                          "3_IB" = 2,
                                                          "3_OB" = 3,
                                                          "3_Run" = 12,
                                                          "4_IB" = 2,
                                                          "4_OB" = 3,
                                                          "4_Run" = 7), 
                                              alternate = c("1_Run" = 2,
                                                            "2_Run" = 2,
                                                            "3_IB" = 2,
                                                            "3_OB" = 2,
                                                            "3_Run" = 4,
                                                            "4_IB" = 2,
                                                            "4_OB" = 2,
                                                            "4_Run" = 3),
                                              map_lims_x = c(-81.98691, -81.68753),
                                              map_lims_y = c(29.07968, 29.535506))